---
name: Additional Tags

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  additional-tags:
    name: 🏷 Additional Tags
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7
      - name: 🚀 Run Release Tracker
        uses: vweevers/additional-tags-action@v2.0.0